app:
  Env: debug
  port: 5005

database:
  dsn: root:123456!@tcp(127.0.0.1:3306)/go_server?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 100
  MaxOpenCons: 1000
  WaitTimeout: 60

redis:
  addr: 127.0.0.1:6379
  DB: 5
  Password: ""

SdeSqlite:
  Path: /sqlite-latest.sqlite

Proxy:
  Host: 127.0.0.1
  Port: 7890